# File: buildDistFiles.rb
#
# Build distribution files for Evothings libraries.

require "fileutils"
require 'time'

include FileUtils::Verbose

### File helpers

def fileRead(filePath)
	File.open(filePath, "r") {
		|f|
		s = f.read
		if (RUBY_VERSION >= "1.9")
			return s.force_encoding("UTF-8")
		else
			return s
		end
	}
end

def fileReadAndDisableAsyncLoading(filePath)
	# Replace evothings.loadScripts and evothings.loadScript
	# with dummy function to disable async script loading since
	# we have all scripts in one file.
	fileRead(filePath)
		.gsub("evothings.loadScripts", "evothings.__NOOP_FUN__")
		.gsub("evothings.loadScript", "evothings.__NOOP_FUN__")
end

def fileWrite(destFile, content)
	File.open(destFile, "w") { |f| f.write(content) }
end

### Build library files

def buildDistFiles
	buildEasyBLE
	buildEddystone
end

def buildEasyBLE
	libsPath = "./libs/evothings/"
	distPath = "./libs/evothings/easyble/easyble.dist.js"

	# Paths to JS files required by easyble.dist.js.
	evothingsbasejs = fileRead(libsPath + "evothings-dist-base.js")
	evothingsjs = fileRead(libsPath + "evothings.js")
	utiljs = fileReadAndDisableAsyncLoading(libsPath + "util/util.js")
	easyblejs = fileReadAndDisableAsyncLoading(libsPath + "easyble/easyble.js")

	# File separator.
	fileSep = "\n\n// --------------------------------------------------\n\n\n"

	# Concatenate files.
	distFile =
		"// File easyble.dist.js " + Time.now.utc.iso8601 + "\n"+
		"// This file was generated by buildDistFiles.rb" + fileSep +
		evothingsbasejs + fileSep +
		evothingsjs + fileSep +
		utiljs  + fileSep +
		easyblejs + fileSep

	# Write out dist JS file.
	fileWrite(distPath, distFile)
end

def buildEddystone
	libsPath = "./libs/evothings/"
	distPath = "./libs/evothings/eddystone/eddystone.dist.js"

	# Paths to JS files required by easyble.dist.js.
	evothingsbasejs = fileRead(libsPath + "evothings-dist-base.js")
	evothingsjs = fileRead(libsPath + "evothings.js")
	utiljs = fileReadAndDisableAsyncLoading(libsPath + "util/util.js")
	easyblejs = fileReadAndDisableAsyncLoading(libsPath + "easyble/easyble.js")
	eddystonejs = fileReadAndDisableAsyncLoading(libsPath + "eddystone/eddystone.js")

	# File separator.
	fileSep = "\n\n// --------------------------------------------------\n\n\n"

	# Concatenate files.
	distFile =
		"// File eddystone.dist.js " + Time.now.utc.iso8601 + "\n" +
		"// This file was generated by buildDistFiles.rb" + fileSep +
		evothingsbasejs + fileSep +
		evothingsjs + fileSep +
		utiljs  + fileSep +
		easyblejs + fileSep +
		eddystonejs + fileSep

	# Write out dist JS file.
	fileWrite(distPath, distFile)
end

### Call main function

buildDistFiles
